apiVersion: v1
kind: Service
metadata:
  name: demo-backserver
spec:
  type: LoadBalancer
  ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
      name: grpc
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: grpc-web
  selector:
    app: demo-backserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backserver
  labels:
    app: demo-backserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backserver
  template:
    metadata:
      labels:
        app: demo-backserver
    spec:
      containers:
        - name: backserver
          image: 192.168.31.42:5000/backserver:latest
      imagePullSecrets:
        - name: myprireg
